BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: PURE_PURE_MMPD
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data1/acsp/toolbox_data/PURE/RawData"    # Raw dataset path, need to be updated
    CACHED_PATH: "/data/rPPG_dataset/processed_dataset"   # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS :
      DATA_TYPE: ['Normalized','Standardized']
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data1/acsp/toolbox_data/PURE/RawData"     # Raw dataset path, need to be updated
    CACHED_PATH: "/data/rPPG_dataset/processed_dataset"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson', 'SNR']
  DATA:
    INFO:
      LIGHT: [LED-low]  # 'LED-low','LED-high','Incandescent','Nature'
      MOTION: [Stationary, Rotation, Talking]  # 'Stationary','Rotation','Talking','Walking'
      EXERCISE: [False]  # True, False
      SKIN_COLOR: [3, 4, 5, 6]  # 3, 4, 5, 6
      GENDER: [male, female]  # 'male','female'
      GLASSER: [True, False] # True, False
      HAIR_COVER: [True, False] # True, False
      MAKEUP: [True, False] # True, False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS:  False    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/data/rPPG_dataset/mat_dataset"          # Raw dataset path, need to be updated
    CACHED_PATH: "/data/rPPG_dataset/processed_dataset"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Normalized','Standardized']
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE: 
  BATCH_SIZE: 8
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH:   "/data/PreTrainedModels/final_model_release/PURE_PURE_MMPD_tscan_Epoch5.pth"